services:
  nginx:
    depends_on:
      wordpress:
       condition: service_healthy
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    restart: always
  mariadb:
    build: ./requirements/mariadb
    expose:
      - "3306:3306"
    healthcheck:
      test: mariadb --user=root
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirements/wordpress
    expose:
      - 9000:9000
    healthcheck:
      test: netstat -an | grep :9000
      interval: 5s
      timeout: 10s
      retries: 20
      start_period: 5s
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - WP_ADMIN=${WP_ADMIN}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_FABIOPASS=${WP_FABIOPASS}
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wordpress:/wordpress
    networks:
      - inception
    restart: always
volumes:
  db:
      name: db
  wordpress:
      name: wordpress
      driver_opts:
        type: "none"
        o: bind
        device: /home/cdupuis/data/wordpress
networks:
  inception:
      
